# 課題３　行列積のスクラッチ

In [1]:
import numpy as np #行列
import pandas as pd #データ分析
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する

$$
A=\left[\begin{array}{ccc}{-1} & {2} & {3} \\ {4} & {-5} & {6} \\ {7} & {8} & {-9}\end{array}\right], B=\left[\begin{array}{ccc}{0} & {2} & {1} \\ {0} & {2} & {-8} \\ {2} & {9} & {-1}\end{array}\right]
$$

AB =  
[6     29  -20]  
       [12   52  38]  
       [-18  -51 -48]  

In [3]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [19]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題3】ある要素の計算を実装

In [20]:
cal = 0
for k in range(3):
    cal += a_ndarray[0, k]*b_ndarray[k, 0]
print(cal)

6


In [21]:
a_ndarray[0,0]

-1

In [22]:
a_ndarray[0][0]

-1

## 【問題4】行列積を行う関数の作成

In [23]:
c_ndarray = np.zeros((3, 3))

In [24]:
c_ndarray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
c_ndarray = np.zeros((3, 3))

for i in range(3):
    for j in range(3):        
        c = 0
        for k in range(3):
            c += a_ndarray[i, k]*b_ndarray[k, j]
        c_ndarray[i, j] = c
print(c_ndarray)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [28]:
np.shape(a_ndarray)

(3, 3)

In [29]:
np.shape(a_ndarray)[0]

3

In [54]:
# (3, 3)同士の行列積  注意： 一般化は問題5で行う
def seki_3(a_ndarray, b_ndarray):
    
    c_ndarray = np.zeros((3, 3))

    for i in range(3):
        for j in range(3):        
            c = 0
            for k in range(3):
                c += a_ndarray[i, k]*b_ndarray[k, j]
            c_ndarray[i, j] = c
    return c_ndarray

In [31]:
seki_3(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [32]:
seki_3(b_ndarray, a_ndarray)

array([[ 15.,  -2.,   3.],
       [-48., -74.,  84.],
       [ 27., -49.,  69.]])

In [33]:
b_ndarray @ a_ndarray

array([[ 15,  -2,   3],
       [-48, -74,  84],
       [ 27, -49,  69]])

## 【問題5】計算が定義されない入力を判定する

In [34]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
f_ndarray = np.array([[1, 3], [-3, 4], [5, 2]])

In [35]:
d_ndarray @ e_ndarray

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [36]:
d_ndarray @ f_ndarray

array([[ 8, 11],
       [49,  4]])

In [37]:
np.shape(d_ndarray)

(2, 3)

In [38]:
np.shape(f_ndarray)

(3, 2)

In [46]:
# (n, m)同士の行列積
def seki(a_ndarray, b_ndarray):
    if np.shape(a_ndarray)[1] != np.shape(b_ndarray)[0]:
        print('サイズが異なるため行列積を計算できません')
        break
    else:
        n=np.shape(a_ndarray)[0]
        m=np.shape(b_ndarray)[1]
        l=np.shape(a_ndarray)[1]
    
        c_ndarray = np.zeros((n, m))

        for i in range(n):
            for j in range(m):        
                c = 0
                for k in range(l):
                    c += a_ndarray[i, k]*b_ndarray[k, j]
                c_ndarray[i, j] = c
    return c_ndarray

SyntaxError: 'break' outside loop (cell_name, line 8)

In [48]:
seki(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [49]:
seki(b_ndarray, a_ndarray)

array([[ 15.,  -2.,   3.],
       [-48., -74.,  84.],
       [ 27., -49.,  69.]])

In [50]:
seki(d_ndarray, e_ndarray)

サイズが異なるため行列積を計算できません


In [51]:
seki(d_ndarray, f_ndarray)

array([[ 8., 11.],
       [49.,  4.]])

In [52]:
seki(a_ndarray, f_ndarray)

array([[  8.,  11.],
       [ 49.,   4.],
       [-62.,  35.]])

In [53]:
a_ndarray @ f_ndarray

array([[  8,  11],
       [ 49,   4],
       [-62,  35]])

## 【問題6】転置

In [55]:
np.transpose(a_ndarray)

array([[-1,  4,  7],
       [ 2, -5,  8],
       [ 3,  6, -9]])

In [56]:
a_ndarray.T

array([[-1,  4,  7],
       [ 2, -5,  8],
       [ 3,  6, -9]])

In [57]:
seki(d_ndarray, e_ndarray)

サイズが異なるため行列積を計算できません


In [58]:
seki(d_ndarray, e_ndarray.T)

array([[ 46.,  -4.],
       [-34.,  73.]])

In [59]:
seki(d_ndarray.T, e_ndarray)

array([[ 33., -28.,   9.],
       [-48.,  41.,  -6.],
       [  9.,  -6.,  45.]])