In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


In [8]:
np.mean(X, axis=0)

array([4.86, 3.31, 1.45, 0.22])

In [9]:
np.var(X, axis=0)

array([0.0764, 0.0849, 0.0105, 0.0056])

In [2]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
X_std

array([[ 0.86828953,  0.65207831, -0.48795004, -0.26726124],
       [ 0.14471492, -1.06391725, -0.48795004, -0.26726124],
       [-0.57885968, -0.37751902, -1.46385011, -0.26726124],
       [-0.94064699, -0.72071813,  0.48795004, -0.26726124],
       [ 0.50650222,  0.99527742, -0.48795004, -0.26726124],
       [ 1.95365143,  2.02487476,  2.43975018,  2.40535118],
       [-0.94064699,  0.3088792 , -0.48795004,  1.06904497],
       [ 0.50650222,  0.3088792 ,  0.48795004, -0.26726124],
       [-1.66422159, -1.40711636, -0.48795004, -0.26726124],
       [ 0.14471492, -0.72071813,  0.48795004, -1.60356745]])

# 【問題1】これまで利用してきたクラスの列挙
 
 
 pd.read_csv()  
 
 plt.plot()  
 plt.scatter()  
  
 LogisticRegression()  

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
 
 インスタンス変数  
 x.shape  
 ? b.T
 
 
 メソッド  
 numpy.sum()  
 numpy.mean()  
 pandas.head()  
 pandas.tail()  
 pandas.isnull()
 pandas.describe()
 
 
 

# 【問題3】標準化クラスをスクラッチで作成

In [20]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)

        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        
        X_scaled = (X - self.mean_) / (self.var_ ** 0.5)
        
        pass
        return X_scaled

In [21]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scaler.mean_))
print("分散 : {}".format(scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [22]:
scaler.mean_

array([4.86, 3.31, 1.45, 0.22])

In [23]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [24]:
(X - scaler.mean_)

array([[ 0.24,  0.19, -0.05, -0.02],
       [ 0.04, -0.31, -0.05, -0.02],
       [-0.16, -0.11, -0.15, -0.02],
       [-0.26, -0.21,  0.05, -0.02],
       [ 0.14,  0.29, -0.05, -0.02],
       [ 0.54,  0.59,  0.25,  0.18],
       [-0.26,  0.09, -0.05,  0.08],
       [ 0.14,  0.09,  0.05, -0.02],
       [-0.46, -0.41, -0.05, -0.02],
       [ 0.04, -0.21,  0.05, -0.12]])

In [25]:
scaler.var_

array([0.0764, 0.0849, 0.0105, 0.0056])

In [26]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


In [27]:
example = ExampleClass(12)

初期値12が設定されました


In [28]:
example.add(11)

In [29]:
example.value

23

In [30]:
example.add(11)

In [31]:
example.value

34

In [42]:
type(2)  == float or int

int

In [102]:
class CalcClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    
#     def check(self, value3):
#         if type(self.value3) == int or type(self.value3) == float:
#             return value3
#         else:
#             print('数値を入力して下さい')
    
    def __init__(self, value):
        self.value = value
        if type(self.value) == int or type(self.value) == float:          
            print("初期値{}が設定されました".format(self.value))
        else:
            print('数値を入力して下さい')
            
    def add(self, value1):
        """
        受け取った引数をself.valueに加える
        """
        try:
            self.value += value1
        except:
            print('数値を入力して下さい')
            
            
    def sub(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        try:
            self.value -= value2
        except:
            print('数値を入力して下さい')
            
    def mul(self, value3):
        """
        受け取った引数をself.valueに加える
        """
        try:
            self.value *= value3
        except:
            print('数値を入力して下さい')
            
    def div(self, value4):
        """
        受け取った引数をself.valueに加える
        """
        try:
            self.value /= value4
        except:
            print('数値を入力して下さい')


# example = CalcClass(5)
# print("value : {}".format(example.value))
# example.add(3.4)
# print("value : {}".format(example.value))

In [110]:
example_1 = CalcClass(5.3)

初期値5.3が設定されました


In [111]:
example_1.add(3.2)

In [112]:
print("value : {}".format(example_1.value))

value : 8.5


In [113]:
example_1.sub(5.2)

In [114]:
print("value : {}".format(example_1.value))

value : 3.3


In [115]:
example_1.mul(3)

In [116]:
print("value : {}".format(example_1.value))

value : 9.899999999999999


In [117]:
example_1.div(2.3)

In [118]:
print("value : {}".format(example_1.value))

value : 4.304347826086956


In [119]:
example_1.mul('ken')

数値を入力して下さい


In [120]:
print("value : {}".format(example_1.value))

value : 4.304347826086956


In [121]:
example_1.add('hu')

数値を入力して下さい


In [122]:
example_1.add(5.3)

In [123]:
print("value : {}".format(example_1.value))

value : 9.604347826086956


In [124]:
example_1 = CalcClass('b')

数値を入力して下さい


In [125]:
print("value : {}".format(example_1.value))

value : b


In [126]:
example_2= CalcClass()

TypeError: __init__() missing 1 required positional argument: 'value'

In [127]:
example_1.mul(3)

In [128]:
print("value : {}".format(example_1.value))

value : bbb


In [129]:
example_1.div(2)

数値を入力して下さい


In [130]:
example_1.add(3)

数値を入力して下さい


In [131]:
print("value : {}".format(example_1.value))

value : bbb


## 問題点
文字列（数字以外）でエラーは出せるが、その際に、インスタンスに文字列が入ってしまっている。  
これを避けたい（インスタンス化しない）が、方法分からず。  

In [132]:
example_2=CalcClass([1, 2, 3])

数値を入力して下さい


# 難しかった、、、